# FLOPs   GMACs   Params.(M)
#  99.38   49.32   1.689
# Throughput (ins./s): 2.445071321282616 
model:
  NAME: BaseSeg
  encoder_args:
    NAME: DeepGCN
    in_channels: 4 
    channels: 64
    emb_dims: 1024
    n_blocks: 14
    conv: 'edge'
    block: 'res'
    k: 16 
    epsilon: 0.2
    use_stochastic: True
    use_dilation: True 
    norm_args: {'norm': 'bn'}
    act_args: {'act': 'relu'}
    is_seg: True
  cls_args:
    NAME: SegHead
    num_classes: 13
    mlps: [512, 256]

batch_size: 8
dataset:
  train:
    voxel_max: 10000